version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/flask_user_app?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=flask_user
      - SPRING_DATASOURCE_PASSWORD=flask_password
      - ADMIN_USERNAME=ggbond
      - ADMIN_PASSWORD=xff123
      - ADMIN_REALNAME=猪猪侠
      - SYSTEM_NAME=望子成龙小学职工管理系统
    depends_on:
      - db
    networks:
      - user-dept-network
    restart: always
    # 开发环境使用
    # volumes:
    #   - ./target:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=flask_user_app
      - MYSQL_USER=flask_user
      - MYSQL_PASSWORD=flask_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user-dept-network
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  user-dept-network:
    driver: bridge

volumes:
  mysql_data: