version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # 或
    # dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      # 数据库配置
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/user_dept_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=user_dept
      - SPRING_DATASOURCE_PASSWORD=user_dept_pwd
      # Redis配置
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      # 系统自定义配置
      - ADMIN_USERNAME=ggbond
      - ADMIN_PASSWORD=xff123
      - ADMIN_REALNAME=猪猪侠
      - SYSTEM_NAME=望子成龙小学职工管理系统
    depends_on:
      - db
      - redis
    networks:
      - user-dept-network
    # restart: always
    # ===生产环境===
    # volumes:
    #   - ./target:/app/target
    #   - ./target/user-dept-system-1.0.0.jar:/app/app.jar
    # command: ["java", "-jar", "/app/app.jar"]
    # ===开发环境===
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    command: ["mvn", "spring-boot:run"]

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=user_dept_system
      - MYSQL_USER=user_dept
      - MYSQL_PASSWORD=user_dept_pwd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - user-dept-network
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - user-dept-network
    restart: always

networks:
  user-dept-network:
    driver: bridge

volumes:
  mysql_data: